apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: management-workers
  namespace: default
spec:
  clusterName: management
  replicas: 3
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: management
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: management
        cluster.x-k8s.io/deployment-name: management-workers
    spec:
      clusterName: management
      version: v1.31.6
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: management-workers
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: management-workers
      failureDomain: fsn1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: management-workers
  namespace: default
spec:
  template:
    spec:
      type: cpx41
      imageName: ubuntu-22.04
      sshKeys:
      - name: ${HETZNER_SSH_KEY}
      placementGroupName: management-workers-pg
      labels:
        cluster: management
        role: worker
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: management-workers
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            eviction-hard: 'imagefs.available<15%,memory.available<500Mi,nodefs.available<10%,nodefs.inodesFree<5%'
            system-reserved: 'cpu=100m,memory=200Mi'
            kube-reserved: 'cpu=100m,memory=200Mi'
          criSocket: unix:///run/containerd/containerd.sock
      preKubeadmCommands:
      - |
        # Harden sysctl settings
        cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes.conf
        kernel.panic = 10
        kernel.panic_on_oops = 1
        vm.overcommit_memory = 1
        vm.swappiness = 0
        net.ipv4.ip_forward = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        EOF
        sudo sysctl -p /etc/sysctl.d/99-kubernetes.conf
      - |
        # Configure containerd
        sudo mkdir -p /etc/containerd
        containerd config default | sudo tee /etc/containerd/config.toml
        sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
        sudo systemctl restart containerd
      - |
        # Install required packages
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      files:
      - path: /etc/kubernetes/kubelet/config.yaml
        owner: root:root
        permissions: "0644"
        content: |
          apiVersion: kubelet.config.k8s.io/v1beta1
          kind: KubeletConfiguration
          cgroupDriver: systemd
          clusterDNS:
          - 10.245.0.10
          clusterDomain: cluster.local
          containerRuntimeEndpoint: unix:///run/containerd/containerd.sock